- name: copiying the mongorepo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: Installing mongo
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
- name: start and enable the servives
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
- name: changing the listining address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: restarting the mongod
  ansible.builtin.service:
    name: mongod
    state: restarted