- name: Installing the nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: Application set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: application
- name: Dependencies install
  ansible.builtin.import_role:
    name: common
    tasks_from: dependencies
- name: Systemd reload
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
- name: Load-Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-schema
- name: restart catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: true
